### ISSUE TITLE
Engine Upgrades Possibly Broken

### ISSUE THREAD

**Issue by PawelW2006** [boot2big/immersive_vehicles_vanity#17]
In the latest version a lot of engine upgrade parts have been added.

However there is no publically available information on how to install them, and all logical ways to install them do not work, engine bench has no modification function and when i hover over engine with part scanner no hitbox appears. Could you make it more clear how it is supposed to work ?

**Comment by boot2big** [comment]
Will rewrite the wiki page to clarify on how parts are installed, but it is simple and is as follows:

Place an IVV engine into the bench (This means it has to be from the same tab as the engine bench itself, as no other packs are currently compatible with these modifications to my knowledge.)
Slots will appear on the engine, allowing you to install modifications onto the engine

https://github.com/boot2big/immersive_vehicles_vanity/wiki/Specialized-Item-Usage#engine-modifications

The reason for this is so that installed modifications are not accidentally removed when switching an engine between vehicles (or removing it in general)

**Comment by boot2big** [comment]
Wiki page has been updated

**Comment by PawelW2006** [comment]
Thanks for Help :)
